/**
 * Constants for Lesson Engine
 */

const PHASE_CONTEXT_SETTING = 'CONTEXT_SETTING';
const PHASE_PREREQUISITES = 'PREREQUISITES';
const PHASE_CORE_INSIGHT = 'CORE_INSIGHT';
const PHASE_SYNTAX_DECOMPOSITION = 'SYNTAX_DECOMPOSITION';
const PHASE_FULL_APPLICATION = 'FULL_APPLICATION';
const PHASE_VERIFICATION = 'VERIFICATION';
const PHASE_CONNECTION = 'CONNECTION';

const PHASE_NAMES = {
  [PHASE_CONTEXT_SETTING]: 'Context Setting',
  [PHASE_PREREQUISITES]: 'Prerequisites',
  [PHASE_CORE_INSIGHT]: 'Core Insight',
  [PHASE_SYNTAX_DECOMPOSITION]: 'Syntax Decomposition',
  [PHASE_FULL_APPLICATION]: 'Full Application',
  [PHASE_VERIFICATION]: 'Verification',
  [PHASE_CONNECTION]: 'Connection & Transition',
};

export {
  PHASE_CONTEXT_SETTING,
  PHASE_PREREQUISITES,
  PHASE_CORE_INSIGHT,
  PHASE_SYNTAX_DECOMPOSITION,
  PHASE_FULL_APPLICATION,
  PHASE_VERIFICATION,
  PHASE_CONNECTION,
  PHASE_NAMES,
};

